Repository abcsys/libem, pull requests merged in 2024-07, with the labels that each got.

#30 Local model support
  Makefile
  examples/local.py
  libem/core/exception.py
  libem/core/model.py
  libem/parameter.py
Labels: lgtm, important

#34 feat: prompt-level batching for match
  Makefile
  benchmark/run.py
  benchmark/util.py
  examples/optimize/profile.py
  examples/optimize/prompt_batch.py
  libem/core/trace.py
  libem/interface.py
  libem/match/function.py
  libem/match/parameter.py
  libem/optimize/function.py
  libem/optimize/interface.py
  libem/prepare/datasets/abt_buy.py
Labels: lgtm, important, feat

#37 feat: async model call and match
  Makefile
  benchmark/README.md
  benchmark/run.py
  benchmark/util.py
  examples/optimize/async_batch.py
  examples/optimize/async_request.py
  examples/optimize/prompt_batch.py
  libem/constant.py
  libem/core/model.py
  libem/core/util.py
  libem/interface.py
  libem/match/function.py
  libem/match/parameter.py
  libem/optimize/function.py
  requirements.txt
Labels: lgtm, important, feat

#39 feat: add support for local model
  .DS_Store
  Makefile
  benchmark/.DS_Store
  benchmark/util.py
  examples/local.py
  libem/core/exception.py
  libem/core/model.py
  libem/optimize/cost/get_cost.py
  libem/parameter.py
Labels: important

#40 feat: add llama3 on mlx to supported model
  Makefile
  benchmark/util.py
  examples/model/llama.py
  libem/core/exception.py
  libem/core/model.py
  libem/optimize/cost/__init__.py
Labels: important, feat

#50 Add llama3 support on llama.cpp for non-apple silicon devices and benchmark results
  Makefile
  benchmark/README.md
  libem/core/model/llama.py
  libem/core/model/openai.py
Labels: lgtm, important, feat

#51 feat: in-context learning with shot selection
  Makefile
  examples/tool/calibrate.py
  examples/tune/rule_from_mistakes.py
  examples/tune/similar_shots.py
  libem/browse/prompt.py
  libem/core/model/openai.py
  libem/core/struct/__init__.py
  libem/core/struct/prompt.py
  libem/match/function.py
  libem/match/parameter.py
  libem/match/prompt.py
  libem/prepare/datasets/__init__.py
  libem/prepare/function.py
  libem/tune/calibrate/function.py
  libem/tune/interface.py
  libem/tune/learn/function.py
  libem/tune/learn/icl/__init__.py
  libem/tune/learn/icl/attentive_shots.py
  libem/tune/learn/icl/given_shots.py
  libem/tune/learn/icl/random_shots.py
  libem/tune/learn/icl/similar_shots.py
  libem/tune/learn/interface.py
  libem/tune/learn/refine/__init__.py
  libem/tune/learn/refine/rule_from_mistakes.py
  libem/tune/learn/strategy/__init__.py
  libem/tune/learn/strategy/random_shots.py
  libem/tune/learn/strategy/similar_shots.py
Labels: feat

#53 feat: always pass train set as part of benchmark but hold off materializing train set until first use
  benchmark/classic/abt_buy.py
  benchmark/classic/amazon_google.py
  benchmark/classic/beer.py
  benchmark/classic/challenging.py
  benchmark/classic/dblp_acm.py
  benchmark/classic/dblp_scholar.py
  benchmark/classic/fodors_zagats.py
  benchmark/classic/itunes_amazon.py
  benchmark/classic/walmart_amazon.py
  benchmark/run.py
  benchmark/util.py
Labels: feat

#56 feat: support indexing for parameter options
  examples/tune/rules.py
  examples/tune/shots.py
  libem/core/struct/__init__.py
  libem/core/struct/parameter.py
  libem/core/struct/prompt.py
Labels: important, feat

#58 feat: redesigned arena api to operate independently of front-end
  .gitignore
  arena/README.md
  arena/demo/arena_home.png
  arena/package-lock.json
  arena/package.json
  arena/public/libby.png
  arena/serve.py
  arena/src/App.css
  arena/src/App.js
  arena/src/Common.js
  arena/src/components/EndScreen.css
  arena/src/components/EndScreen.js
  arena/src/components/ErrorPopup.js
  arena/src/components/Timer.js
  arena/src/pages/Leaderboard.js
  arena/src/pages/MainMenu.css
  arena/src/pages/MainMenu.js
  arena/src/pages/Match.css
  arena/src/pages/Match.js
  arena/webpack.config.js
Labels: lgtm, important, arena, feat

#59 fix arena frontend bug and add unit test file
  arena/Makefile
  arena/src/pages/Match.js
  test/arena.py
Labels: bug, lgtm

#60 feat(match): support structured input parsing for dict and pair
  benchmark/util.py
  libem/core/struct/parameter.py
  libem/match/interface/__init__.py
  libem/match/interface/struct.py
  libem/match/parameter.py
  libem/parameter.py
Labels: important, feat
