Repository abcsys/libem, pull requests merged in 2024-06, with the labels that each got.

#22 Libem Arena
  .gitignore
  arena/.babelrc
  arena/README.md
  arena/demo/arena_home.png
  arena/demo/arena_leaderboard.png
  arena/demo/arena_result.png
  arena/demo/arena_select.png
  arena/index.js
  arena/package-lock.json
  arena/package.json
  arena/public/index.html
  arena/public/main.js
  arena/serve.py
  arena/src/App.css
  arena/src/App.js
  arena/src/Constants.js
  arena/src/components/EndScreen.css
  arena/src/components/EndScreen.js
  arena/src/components/Leaderboard.css
  arena/src/components/Leaderboard.js
  arena/src/components/MainMenu.css
  arena/src/components/MainMenu.js
  arena/src/components/Selection.css
  arena/src/components/Selection.js
  arena/src/components/Timer.js
  arena/webpack.config.js
  libem/prepare/datasets/abt_buy.py
  libem/prepare/datasets/amazon_google.py
  libem/prepare/datasets/challenging.py
  libem/prepare/datasets/dblp_acm.py
  libem/prepare/datasets/dblp_scholar.py
  libem/prepare/datasets/sample_demo.py
  libem/prepare/datasets/walmart_amazon.py
  requirements.txt
Labels: lgtm, important

#24 fixed major bugs with arena
  arena/README.md
  arena/package.json
  arena/serve.py
  arena/src/components/Leaderboard.js
  arena/src/components/Selection.js
  requirements.txt
Labels: bug, lgtm

#26 feat: add blocking
  Makefile
  benchmark/README.md
  benchmark/classic/__init__.py
  benchmark/classic/abt_buy.py
  benchmark/classic/amazon_google.py
  benchmark/classic/beer.py
  benchmark/classic/challenging.py
  benchmark/classic/dblp_acm.py
  benchmark/classic/dblp_scholar.py
  benchmark/classic/fodors_zagats.py
  benchmark/classic/itunes_amazon.py
  benchmark/classic/walmart_amazon.py
  benchmark/run.py
  benchmark/util.py
  examples/tool/block.py
  libem/block/__init__.py
  libem/block/function.py
  libem/block/parameter.py
  libem/interface.py
  libem/match/function.py
  requirements.txt
  setup.py
Labels: lgtm, important

#28 feat: page routing, collape result popup, save session token to cookies
  arena/package-lock.json
  arena/package.json
  arena/serve.py
  arena/src/App.css
  arena/src/App.js
  arena/src/Common.js
  arena/src/Constants.js
  arena/src/pages/EndScreen.css
  arena/src/pages/EndScreen.js
  arena/src/pages/Leaderboard.css
  arena/src/pages/Leaderboard.js
  arena/src/pages/MainMenu.css
  arena/src/pages/MainMenu.js
  arena/src/pages/Match.css
  arena/src/pages/Match.js
  arena/src/pages/Timer.js
  arena/webpack.config.js
Labels: lgtm, arena

#29 Add make data to download libem-sample-data
  Makefile
Labels: lgtm
