Repository abcsys/libem, pull requests merged in 2024-08, with the labels that each got.

#73 fix: create a deep copy of args in benchmark
  benchmark/run.py
Labels: bug, lgtm

#81 feat: add duckdb and mongodb integration to cluster
  Makefile
  examples/apps/cluster.py
  examples/apps/integration/duckdb_cluster.py
  examples/apps/integration/mongodb_cluster.py
  libem/resolve/cluster/integrations/duckdb.py
  libem/resolve/cluster/integrations/mongodb.py
  libem/resolve/cluster/integrations/pandas.py
  libem/resolve/cluster/interface.py
  requirements.txt
Labels: lgtm, feat

#82 fix: preserve duplicate records in cluster
  libem/resolve/cluster/function.py
Labels: bug, lgtm

#85 refactor: simplify cluster id assignment
  libem/resolve/cluster/function.py
Labels: lgtm

#71 feat: add support for llama 3.1
  benchmark/Llama.md
  benchmark/README.md
  benchmark/classic/amazon_google.py
  benchmark/classic/challenging.py
  benchmark/classic/dblp_acm.py
  benchmark/classic/dblp_scholar.py
  benchmark/classic/fodors_zagats.py
  benchmark/classic/itunes_amazon.py
  benchmark/classic/walmart_amazon.py
  libem/core/model/__init__.py
  libem/core/model/llama.py
  libem/match/function.py
  libem/match/prompt.py
  libem/optimize/cost/__init__.py
  libem/parameter.py
Labels: lgtm, important, feat

#87 feat: allow dynamic value for index
  benchmark/Llama.md
  benchmark/README.md
  libem/core/struct/parameter.py
  libem/core/struct/prompt.py
  libem/match/function.py
  libem/match/parameter.py
  libem/match/prompt.py
  libem/resolve/cluster/function.py
Labels: feat

#89 feat: add benchmark results for all gpt models and minor bug fix
  benchmark/README.md
  benchmark/suite/gpt_35_turbo.py
  benchmark/suite/gpt_4.py
  benchmark/suite/gpt_4_turbo.py
  benchmark/suite/gpt_4o.py
  benchmark/suite/gpt_4o_mini.py
  benchmark/suite/util.py
Labels: feat

#92 refactor: strict output for gpt-4o-08-06 and add avg results
  benchmark/README.md
  benchmark/__init__.py
  benchmark/suite/block.py
  benchmark/suite/gpt_35_turbo.py
  benchmark/suite/gpt_4.py
  benchmark/suite/gpt_4_turbo.py
  benchmark/suite/gpt_4o.py
  benchmark/suite/gpt_4o_mini.py
  benchmark/suite/llama3.py
  libem/match/prompt.py
Labels: feat

#93 feat: add option to partition by keys when blocking
  libem/block/function.py
  libem/block/interface.py
  test/block.py
Labels: lgtm, important, feat

#86 Add anthropic model support
  Makefile
  benchmark/README.md
  cli/libem
  examples/model/claude.py
  libem/core/model/__init__.py
  libem/core/model/claude.py
  libem/match/prompt.py
  libem/parameter.py
  requirements.txt
Labels: lgtm, feat

#95 feat: add suite plots
  benchmark/__init__.py
  benchmark/run.py
  benchmark/suite/__init__.py
  benchmark/suite/batch.py
  benchmark/suite/plot/batch_size.py
  benchmark/suite/plot/model_cost_trend.py
  benchmark/suite/plot/model_f1.py
  benchmark/suite/plot/model_throughput.py
  benchmark/suite/plot/util.py
Labels: lgtm, feat
